#!/usr/bin/python3

import pathlib, shutil, re
import meta_file, patcher

# female class patterns
female_regex = re.compile(
    r""".*(
                          p[a-z]+w_ # most of female classes fall into this pattern
                          |pmyf_ # Woosa's ID is special
                          )""",
    re.VERBOSE,
)


def is_female(block: meta_file.FileBlock):
    fullPath = str(block.fullPath())
    return female_regex.match(fullPath)


def is_male(block: meta_file.FileBlock):
    fullPath = str(block.fullPath())
    return not female_regex.match(fullPath)


def patch_models(what: str, outDir: pathlib.Path, meta: meta_file.MetaFile, inclusions: callable = None):
    # search through model files of all classes, select every .pac files under player folder with name "38_underwear"
    def is_underwear_model(block: meta_file.FileBlock):
        if "38_underwear" not in block.folderName:
            return False
        if inclusions is not None and not inclusions(block):
            return False
        return True

    patcher.hide_player_models(what, outDir, meta, is_underwear_model)


def patch_textures(what: str, outDir: pathlib.Path, meta: meta_file.MetaFile, inclusions: callable = None):
    # file name must contain either "_##_uw_" or "_99_ub_"
    pattern = re.compile(r"_\d{2}_uw_|_99_ub_")

    def is_underwear_texture(block: meta_file.FileBlock):
        if not pattern.search(block.fileName):
            return False
        if inclusions is not None and not inclusions(block):
            return False
        return True

    patcher.patch_player_ao_textures(what, outDir, meta, is_underwear_texture)


def remove_underwear(outDir: pathlib.Path, meta: meta_file.MetaFile):
    # patch_models(outDir, meta)
    # patch_textures(outDir, meta)

    # female
    patch_models("Hide female underwear models...", outDir / "_female", meta, is_female)
    patch_textures("Patch female underwear AO textures...", outDir / "_female", meta, is_female)

    # male free items
    patch_models("Hide male underwear models...", outDir / "_male", meta, is_male)
    patch_textures("Patch male underwear AO textures", outDir / "_male", meta, is_male)

    # generate a readme file
    with open(outDir / ".README.md", "w") as f:
        f.write(
            """# What's this?

Patch files to remove underwear model and textures from
all playable classes, except Shai, up to release of Scholar.

Generated by Midnight Xyzw (https://github.com/midnightxyzw/bdo-nsfw)

# How to use it?

- Put it under files_to_patch folder.
- Run PartCutGen.exe to refresh your partcuts_desc.xml
- Run Meta Injector.exe to patch your game.
"""
        )
