#!/usr/bin/python3

import pathlib, abc, re
import meta_file, patcher

# female class patterns
female_regex = re.compile(
    r""".*(
                          p[a-z]+w_ # most of female classes fall into this pattern
                          |pmyf_ # Woosa's ID is special
                          )""",
    re.VERBOSE,
)

class UnderwearModelCategorizer(patcher.FileCategorizer):
    def categorize(self, block: meta_file.FileBlock):
        if "38_underwear" not in block.folderName:
            return None
        fullPath = str(block.fullPath())
        return "female" if female_regex.match(fullPath) else "male"

class UnderwearTextureCategorizer(patcher.FileCategorizer):
    def __init__(self):
        # file name must contain either "_##_uw_" or "_99_ub_"
        self.pattern = re.compile(r"_\d{2}_uw_|_99_ub_")

    def categorize(self, block: meta_file.FileBlock):
        if not self.pattern.search(block.fileName):
            return None
        fullPath = str(block.fullPath())
        return "female" if female_regex.match(fullPath) else "male"

def remove_underwear(outDir: pathlib.Path, meta: meta_file.MetaFile):
    patcher.hide_player_models("Hide underwear models...", outDir, meta, UnderwearModelCategorizer())
    patcher.patch_player_ao_textures("Patch underwear AO textures...", outDir, meta, UnderwearTextureCategorizer())
    with open(outDir / ".README.md", "w") as f:
        f.write(
            """# What's this?

Patch files to remove underwear model and textures from
all playable classes, except Shai, up to release of Scholar.

Generated by Midnight Xyzw (https://github.com/midnightxyzw/bdo-nsfw)

# How to use it?

- Put it under files_to_patch folder.
- Run PartCutGen.exe to refresh your partcuts_desc.xml
- Run Meta Injector.exe to patch your game.
"""
        )
